style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Bartman0/git-chglog-test
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    title_maps:
      feat: Features
      feature: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      doc: Documentation
  header:
    #pattern: "^(\\w*)\\:\\s(.*)$"
    pattern: "^(\\w*)\\:\\s(.*)i|Merge branch '(\\w*)/(.*)'.*$"
    pattern_maps:
      - Type
      - Subject
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
